export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  eSignProvider: process.env.ESIGN_PROVIDER ?? "other",
  eSignYousignApiKey: process.env.ESIGN_YOUSIGN_API_KEY ?? "",
  eSignYousignBaseUrl: process.env.ESIGN_YOUSIGN_BASE_URL ?? "",
  eSignDocusignAccountId: process.env.ESIGN_DOCUSIGN_ACCOUNT_ID ?? "",
  eSignDocusignAccessToken: process.env.ESIGN_DOCUSIGN_ACCESS_TOKEN ?? "",
  eSignDocusignBasePath: process.env.ESIGN_DOCUSIGN_BASE_PATH ?? "",
};
